# Generated by Django 4.2.6 on 2023-10-29 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes_app", "0003_step_ingredients"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="rec_how_do",
        ),
    ]
