# Generated by Django 4.2.6 on 2023-10-29 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes_app", "0004_remove_recipe_rec_how_do"),
    ]

    operations = [
        migrations.AlterField(
            model_name="step",
            name="step_number",
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name="step",
            name="step_text",
            field=models.TextField(),
        ),
    ]
