# Generated by Django 4.2.6 on 2023-10-29 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recipes_app", "0006_ingredients_ingr_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="rec_author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.DeleteModel(
            name="Author",
        ),
    ]
