# Generated by Django 4.2.6 on 2024-02-17 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contacts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kod", models.CharField(max_length=50)),
                ("kont_tel", models.CharField(max_length=250)),
                ("kont_fio", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Hospices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_hosp", models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name="VPS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_vps", models.CharField(max_length=260)),
            ],
        ),
        migrations.CreateModel(
            name="Pacient",
            fields=[
                (
                    "kod_p",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("data_registracii", models.DateTimeField(blank=True)),
                ("data_vkl_reestr", models.DateField(blank=True)),
                ("data_na_uchet", models.DateField(blank=True)),
                ("pacient", models.CharField(max_length=250)),
                ("pol", models.CharField(blank=True, max_length=10)),
                ("data_rozhd", models.DateField(blank=True)),
                ("gr_status", models.CharField(blank=True, max_length=100)),
                ("adres", models.CharField(blank=True, max_length=500)),
                ("adres_fakt", models.CharField(blank=True, max_length=500)),
                ("dul", models.CharField(blank=True, max_length=150)),
                ("serija_nomer", models.CharField(blank=True, max_length=50)),
                ("kem_vydan", models.CharField(blank=True, max_length=150)),
                ("svidetelstvo", models.CharField(blank=True, max_length=150)),
                ("snils", models.CharField(blank=True, max_length=50)),
                ("polis_oms", models.CharField(blank=True, max_length=50)),
                ("invalidnost", models.CharField(blank=True, max_length=50)),
                ("osnovnoj_mkb10", models.CharField(blank=True, max_length=150)),
                ("osn_kont_lico", models.CharField(blank=True, max_length=150)),
                ("data_vk", models.DateField(blank=True)),
                ("dokument_vk", models.CharField(blank=True, max_length=150)),
                ("organizacija_vk", models.CharField(blank=True, max_length=150)),
                ("razreshenie_dzm", models.CharField(blank=True, max_length=50)),
                ("data_razreshenija_dzm", models.DateField(blank=True)),
                ("nomer_razreshenija_dzm", models.CharField(blank=True, max_length=50)),
                ("status_pacienta", models.CharField(blank=True, max_length=150)),
                ("data_prekr_okaz_pmp", models.DateField(blank=True)),
                ("osnovanija_prekr_pmp", models.CharField(blank=True, max_length=150)),
                ("data_smerti", models.DateField(blank=True)),
                ("rc", models.CharField(blank=True, max_length=10)),
                ("bk", models.CharField(blank=True, max_length=10)),
                ("osn_diagnoz_obr", models.TextField(blank=True)),
                ("komment", models.TextField(blank=True)),
                ("svo", models.CharField(blank=True, max_length=50)),
                ("kanal_post_inf", models.CharField(blank=True, max_length=150)),
                ("kto_napravil", models.CharField(blank=True, max_length=150)),
                ("data_poluch_ids", models.DateField(blank=True)),
                ("amb_karta", models.CharField(blank=True, max_length=150)),
                ("pom_udalenija", models.CharField(blank=True, max_length=10)),
                ("gr", models.CharField(blank=True, max_length=10)),
                (
                    "kur_podr",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="search_man.vps",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Kis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_rozhd", models.DateField(blank=True)),
                ("snils", models.CharField(max_length=50)),
                ("adres_region", models.CharField(blank=True, max_length=500)),
                ("adres", models.CharField(blank=True, max_length=500)),
                ("grazhdanstvo", models.CharField(blank=True, max_length=150)),
                ("soc_status", models.CharField(blank=True, max_length=150)),
                ("data_gospit", models.DateTimeField()),
                ("data_vipiski", models.DateTimeField(blank=True)),
                ("ishod", models.CharField(blank=True, max_length=150)),
                ("telefon", models.CharField(blank=True, max_length=150)),
                ("kont_inf", models.CharField(blank=True, max_length=150)),
                (
                    "otdelenie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="search_man.hospices",
                    ),
                ),
                (
                    "pacient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="search_man.pacient",
                    ),
                ),
            ],
        ),
    ]
