# Generated by Django 4.2.6 on 2024-02-17 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("search_man", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contacts",
            name="kod",
        ),
        migrations.AddField(
            model_name="contacts",
            name="kont_pac",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="search_man.pacient",
            ),
            preserve_default=False,
        ),
    ]
