# Generated by Django 4.2.6 on 2024-02-19 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("search_man", "0002_remove_contacts_kod_contacts_kont_pac"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contacts",
            name="kont_pac",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="cont",
                to="search_man.pacient",
            ),
        ),
        migrations.AlterField(
            model_name="kis",
            name="kont_inf",
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
