# Generated by Django 4.2.6 on 2023-11-25 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hospis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("beds_gz", models.IntegerField()),
                ("on_activ", models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="Pacient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("pat_name", models.CharField(max_length=255)),
                ("birthday", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("м", "Мужчина"), ("ж", "Женщина")], max_length=50
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ZayavkaNaGospit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "now_status",
                    models.CharField(
                        choices=[
                            ("Ожидает одобрения", "Ожидает одобрения"),
                            ("Одобрена", "Одобрена"),
                            ("Отложена", "Отложена"),
                            ("Отменена", "Отменена"),
                            ("Умер", "Умер"),
                            ("Госпитализирован", "Госпитализирован"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "pokaz_on_gospit",
                    models.CharField(
                        choices=[
                            ("Мед план", "Мед план"),
                            ("Мед срочно", "Мед срочно"),
                            ("ОРДП план", "ОРДП план"),
                        ],
                        max_length=15,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("location_from", models.CharField(max_length=150)),
                ("med_critary", models.IntegerField(max_length=5)),
                ("reason_hospit", models.TextField()),
                (
                    "type_transport",
                    models.CharField(
                        choices=[
                            ("СМП", "СМП"),
                            ("Машина с  носилками", "Машина с  носилками"),
                            ("Cобственным транспортом", "Cобственным транспортом"),
                            ("ЦЭМП", "ЦЭМП"),
                            ("Умер", "Умер"),
                            ("Машина без носилок", "Машина без носилок"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "who_agreed_zayav",
                    models.CharField(
                        choices=[
                            ("Зав_ОВПП", "Зав_ОВПП"),
                            ("Зав_филиалом", "Зав_филиалом"),
                            ("Зав_ОДРП", "Зав_ОДРП"),
                            ("Врач_КЦ", "Врач_КЦ"),
                            ("Врач_деж_админ", "Врач_деж_админ"),
                            ("Глав_врач", "Глав_врач"),
                            ("Зам_по_амб", "Зам_по_амб"),
                            ("Зам_по_стац", "Зам_по_стац"),
                            ("ГВС", "ГВС"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "pacient_data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wait_list_app.pacient",
                    ),
                ),
                (
                    "prefer_filial",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wait_list_app.hospis",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReportBeds",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("beds_remont", models.IntegerField()),
                ("beds_dop", models.IntegerField()),
                ("m_free", models.IntegerField()),
                ("f_free", models.IntegerField()),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("note", models.CharField(max_length=150)),
                (
                    "filial",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wait_list_app.hospis",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Gospitalization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_gospit", models.DateTimeField()),
                ("mksb", models.CharField(max_length=20)),
                (
                    "zayavka",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wait_list_app.zayavkanagospit",
                    ),
                ),
            ],
        ),
    ]
