# Generated by Django 4.2.6 on 2023-10-14 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wait_list_app", "0002_rename_med_org_medorgmod_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reportbedsmod",
            old_name="name_meg_org",
            new_name="meg_org",
        ),
    ]
