# Generated by Django 4.2.6 on 2023-10-14 08:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("wait_list_app", "0004_rename_meg_org_reportbedsmod_med_org"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportbedsmod",
            name="create_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
