# Generated by Django 4.2.6 on 2023-10-14 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wait_list_app", "0005_reportbedsmod_create_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="ZayavkaNaGospit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fio", models.CharField(max_length=150, unique=True)),
                ("birthday", models.DateField(unique=True)),
                ("diagnoz", models.CharField(max_length=150)),
                ("dateVk", models.DateField()),
                (
                    "quickly_categor",
                    models.CharField(
                        choices=[
                            ("Мед_план", "Мед_план"),
                            ("Соц_план", "Соц_план"),
                            ("Мед_CITO", "Мед_CITO"),
                            ("Соц_CITO", "Соц_CITO"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                ("comment", models.TextField()),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                (
                    "med_org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wait_list_app.medorgmod",
                    ),
                ),
            ],
        ),
    ]
