# Generated by Django 4.2.6 on 2023-10-14 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wait_list_app", "0006_zayavkanagospit"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(max_length=20)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
