# Generated by Django 4.2.6 on 2023-10-14 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wait_list_app", "0007_client"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportbedsmod",
            name="note",
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
