# Generated by Django 4.2.6 on 2023-10-19 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wait_list_app', '0008_reportbedsmod_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospisname', models.CharField(max_length=150)),
                ('hosp_m_dostup_bed', models.IntegerField()),
                ('hosp_f_dostup_bed', models.IntegerField()),
                ('hosp_m_busy_bed', models.IntegerField()),
                ('hosp_f_busy_bed', models.IntegerField()),
                ('hosp_m_free_bed', models.IntegerField()),
                ('hosp_f_free_bed', models.IntegerField()),
                ('hosp_m_wait_bed', models.IntegerField()),
                ('hosp_f_wait_bed', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=150)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('on_activ', models.BooleanField()),
            ],
        ),
    ]
