# Generated by Django 4.2.6 on 2023-10-20 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wait_list_app', '0009_hospis_userpatient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportbedsmod',
            old_name='f_employ',
            new_name='f_dop',
        ),
        migrations.RenameField(
            model_name='reportbedsmod',
            old_name='m_employ',
            new_name='f_gz',
        ),
        migrations.AddField(
            model_name='reportbedsmod',
            name='f_remont',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportbedsmod',
            name='m_dop',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportbedsmod',
            name='m_gz',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportbedsmod',
            name='m_remont',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportbedsmod',
            name='mf_dop',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportbedsmod',
            name='mf_free',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportbedsmod',
            name='mf_gz',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportbedsmod',
            name='mf_remont',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
